services:
  nest-api:
    build: .

    ports:
      - "3000:3000"       

    depends_on:
      - mysql-db          

    environment:
    - PORT=3000
    - NODE_ENV=development

    volumes:
      - .:/app            
      - /app/node_modules

    command: npm run start:dev

  mysql-db:
    image: mysql:8.0

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bdveiculos
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=senhabanco
      - MYSQL_TCP_PORT=3307
    ports:
      - "3307:3307"

    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
